package mybatis.dao;

import java.util.List;
import mybatis.pojo.Admin;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated
     */
    int insert(Admin record);
    int update(Admin record);
    int updatestate(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated
     */
    java.util.List<mybatis.pojo.Admin> selectAll();
}