package mybatis.dao;

import java.util.List;
import mybatis.pojo.Program;

public interface ProgramMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program
     *
     * @mbggenerated
     */
    int insert(Program record);
    int updatenumber(Program record);
    int updataProgramById(Program program);
    int updateall();
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program
     *
     * @mbggenerated
     */
    java.util.List<mybatis.pojo.Program> selectAll();
    
    java.util.List<mybatis.pojo.Program> selectAllByIdAsc();
    
    java.util.List<mybatis.pojo.Program>  selectAllByNum();
    
    Program selectById(int programid);
    
    int deleteProgramById(int programid);
    /**
     * ����Ʊ��
     * @param record
     * @return
     */
    int updatenum(Program record);
}