package mybatis.dao;

import java.util.List;

import mybatis.pojo.Program;
import mybatis.pojo.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);
   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    java.util.List<mybatis.pojo.User> selectAll();
    /**
     * ��ѯͶƱ����
     * @param name
     * @return
     */
    User vote(String name);
    
    int updatevote(User user);
    int updateallu();
   
}