package mybatis.pojo;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.selectnum
     *
     * @mbggenerated
     */
    private Integer selectnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminname
     *
     * @mbggenerated
     */
    private String adminname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminpassword
     *
     * @mbggenerated
     */
    private String adminpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.selectnum
     *
     * @return the value of admin.selectnum
     *
     * @mbggenerated
     */
    public Integer getSelectnum() {
        return selectnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.selectnum
     *
     * @param selectnum the value for admin.selectnum
     *
     * @mbggenerated
     */
  

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.state
     *
     * @return the value of admin.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.state
     *
     * @param state the value for admin.state
     *
     * @mbggenerated
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminname
     *
     * @return the value of admin.adminname
     *
     * @mbggenerated
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminname
     *
     * @param adminname the value for admin.adminname
     *
     * @mbggenerated
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminpassword
     *
     * @return the value of admin.adminpassword
     *
     * @mbggenerated
     */
    public String getAdminpassword() {
        return adminpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminpassword
     *
     * @param adminpassword the value for admin.adminpassword
     *
     * @mbggenerated
     */
    public void setAdminpassword(String adminpassword) {
        this.adminpassword = adminpassword;
    }

    /**
     * @param integer
     */
    public void setSelectnum(Integer selectnum) {
        this.selectnum = selectnum;
        
    }

    /**
     * @param integer
     */
    public void setState(Integer integer) {
        this.state = integer;
        
    }

    /**
     * @param integer
     */
  
    /**
     * @param integer
     */
 
    /**
     * @param integer
     */
  
}