package mybatis.pojo;

public class Program {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.pictureadr
     *
     * @mbggenerated
     */
    private String pictureadr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.programname
     *
     * @mbggenerated
     */
    private String programname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.programid
     *
     * @mbggenerated
     */
    private Integer programid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.programnum
     *
     * @mbggenerated
     */
    private Integer programnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.pictureadr
     *
     * @return the value of program.pictureadr
     *
     * @mbggenerated
     */
    public String getPictureadr() {
        return pictureadr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.pictureadr
     *
     * @param pictureadr the value for program.pictureadr
     *
     * @mbggenerated
     */
    public void setPictureadr(String pictureadr) {
        this.pictureadr = pictureadr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.programname
     *
     * @return the value of program.programname
     *
     * @mbggenerated
     */
    public String getProgramname() {
        return programname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.programname
     *
     * @param programname the value for program.programname
     *
     * @mbggenerated
     */
    public void setProgramname(String programname) {
        this.programname = programname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.programid
     *
     * @return the value of program.programid
     *
     * @mbggenerated
     */
    public Integer getProgramid() {
        return programid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.programid
     *
     * @param programid the value for program.programid
     *
     * @mbggenerated
     */
    public void setProgramid(Integer programid) {
        this.programid = programid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.programnum
     *
     * @return the value of program.programnum
     *
     * @mbggenerated
     */
    public Integer getProgramnum() {
        return programnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.programnum
     *
     * @param programnum the value for program.programnum
     *
     * @mbggenerated
     */
    public void setProgramnum(Integer programnum) {
        this.programnum = programnum;
    }
}